// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskCRUDContoller.Data;

#nullable disable

namespace TaskCRUDContoller.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230925022620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("TaskCRUDContoller.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            Description = "This is Task 1",
                            DueDate = new DateTime(2023, 9, 25, 8, 56, 20, 587, DateTimeKind.Local).AddTicks(7582),
                            IsCompleted = false,
                            Title = "Task 1"
                        },
                        new
                        {
                            TaskId = 2,
                            Description = "This is Task 2",
                            DueDate = new DateTime(2023, 9, 25, 8, 56, 20, 587, DateTimeKind.Local).AddTicks(7595),
                            IsCompleted = true,
                            Title = "Task 2"
                        },
                        new
                        {
                            TaskId = 3,
                            Description = "This is Task 3",
                            DueDate = new DateTime(2023, 9, 25, 8, 56, 20, 587, DateTimeKind.Local).AddTicks(7596),
                            IsCompleted = false,
                            Title = "Task 3"
                        },
                        new
                        {
                            TaskId = 4,
                            Description = "This is Task 4",
                            DueDate = new DateTime(2023, 9, 25, 8, 56, 20, 587, DateTimeKind.Local).AddTicks(7597),
                            IsCompleted = true,
                            Title = "Task 4"
                        },
                        new
                        {
                            TaskId = 5,
                            Description = "This is Task 5",
                            DueDate = new DateTime(2023, 9, 25, 8, 56, 20, 587, DateTimeKind.Local).AddTicks(7598),
                            IsCompleted = false,
                            Title = "Task 5"
                        },
                        new
                        {
                            TaskId = 6,
                            Description = "This is Task 6",
                            DueDate = new DateTime(2023, 9, 25, 8, 56, 20, 587, DateTimeKind.Local).AddTicks(7599),
                            IsCompleted = true,
                            Title = "Task 6"
                        },
                        new
                        {
                            TaskId = 7,
                            Description = "This is Task 7",
                            DueDate = new DateTime(2023, 9, 25, 8, 56, 20, 587, DateTimeKind.Local).AddTicks(7600),
                            IsCompleted = false,
                            Title = "Task 7"
                        },
                        new
                        {
                            TaskId = 8,
                            Description = "This is Task 8",
                            DueDate = new DateTime(2023, 9, 25, 8, 56, 20, 587, DateTimeKind.Local).AddTicks(7602),
                            IsCompleted = true,
                            Title = "Task 8"
                        },
                        new
                        {
                            TaskId = 9,
                            Description = "This is Task 9",
                            DueDate = new DateTime(2023, 9, 25, 8, 56, 20, 587, DateTimeKind.Local).AddTicks(7602),
                            IsCompleted = false,
                            Title = "Task 9"
                        },
                        new
                        {
                            TaskId = 10,
                            Description = "This is Task 10",
                            DueDate = new DateTime(2023, 9, 25, 8, 56, 20, 587, DateTimeKind.Local).AddTicks(7604),
                            IsCompleted = true,
                            Title = "Task 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
